# Generated by Django 4.1.5 on 2023-01-27 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CharitySolutionAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userspost',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='default'),
        ),
    ]
