# Generated by Django 4.1.5 on 2023-01-27 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CharitySolutionAPI', '0003_alter_userspost_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userspost',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
